# Base configs
# baseurl: "https://souravdebnath.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "GTM-TWTH2Q8F"

# UI configs
title: "Photography by Sourav Debnath"
subtitle: "See the world through my eyes!"
author: "Sourav Debnath"
header:
 title: "Photography"
 subtitle: "by Sourav Debnath"
footer:
 name: "Hey there, my name is Sourav"
 bio: "I am a Product Manager and an AI enthusiast from India. Love creating products solving business problems in life and trying out photography on the sidelines."
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://twitter.com/souravdebnath27"
  instagram: "https://www.instagram.com/debu11/"
  # dribbble: "https://dribbble.com/sourav27"
  linkedin: "https://www.linkedin.com/in/souravdebnath/"
  github: "https://github.com/Sourav27"
